---
- name: Kubernetes health check with Ansible
  hosts: localhost
  tasks:
  - name: Check health of a specific pod
    community.kubernetes.k8s_info:
      api_version: v1
      kind: Pod
      namespace: default
      name: "{{ POD_NAME }}"
    register: pod_info

  - name: Send pod status directly to Elasticsearch
    uri:
      url: "http://your-elasticsearch-endpoint/status"
      method: POST
      headers:
        Content-Type: "application/json"
      body_format: json
      body: 
        status: "{{ pod_info.resources[0].status.phase }}"
    register: response

  - name: Print Elasticsearch response
    debug:
      var: response.json

